name: PortableCraftingMenu
version: 1.6.8
main: CodsXBlastin\PCM\Main
api: 3.0.0
author: CodsXBlastin
mcpe-protocol: [407, 408, 419, 422]
website: https://github.com/codsxblastin/PortableCraftingMenu

commands:
 craft:
  description: Opens Portable Crafting Table
  usage: "/craft"

permissions:
 pcm.command:
  default: true
